included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
    - Douyin/
disabled_rules: # 执行时排除掉的规则
  - colon
  - comma
  - control_statement
  - line_length
  # - vertical_whitespace 垂直方向的一行限制为一行
  - trailing_whitespace
  - variable_name # 声明变量
  - void_return # -> () 使用 -> Void替代
  - empty_count # isEmpty代替.count == 0
  - shorthand_operator # 操作运算符 += -=等等
  - force_try # 强制解包
  - trailing_comma
  - unused_closure_parameter
  - empty_parentheses_with_trailing_closure
  - force_cast
  - number_separator
  - unused_optional_binding
  - unneeded_break_in_switch
  - syntactic_sugar
  - multiple_closures_with_trailing_closure
  - block_based_kvo
  - function_parameter_count # 函数参数不能超过5个
  - type_name
  - empty_enum_arguments
  - cyclomatic_complexity
  - for_where
  - function_body_length
  - nesting
  - type_body_length
  - legacy_constructor
  - implicit_getter
  - unused_enumerated
  - vertical_parameter_alignment
  # - todo
  - private_unit_test # 单元测试相关
opt_in_rules: # 一些规则仅仅是可选的
  - empty_count
  - missing_docs
  # 可以通过执行如下指令来查找所有可用的规则:
  # swiftlint rules
excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
  - Carthage
  - Pods

# 可配置的规则可以通过这个配置文件来自定义
# 二进制规则可以设置他们的严格程度
force_cast: warning # 隐式
force_try:
severity: warning # 显式
# 同时有警告和错误等级的规则，可以只设置它的警告等级
# 隐式
line_length: 200
# 可以通过一个数组同时进行隐式设置
type_body_length:
  - 300 # warning
  - 400 # error
# 或者也可以同时进行显式设置
file_length:
  warning: 1500
  error: 2000
# 命名规则可以设置最小长度和最大程度的警告/错误
# 此外它们也可以设置排除在外的名字
type_name:
  min_length: 4 # 只是警告
  max_length: # 警告和错误
    warning: 40
    error: 50
  excluded: iPhone # 排除某个名字
identifier_name:
  min_length: # 只有最小长度
    error: 4 # 只有错误
  excluded: # 排除某些名字
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle, junit, html, emoji)
