
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'Douyin' do

    pod 'Alamofire'
    pod 'HandyJSON'
    pod 'SnapKit', '~> 4.2.0'
    pod 'Starscream', '~> 3.0.6'
    # 拉取master
    # pod 'libwebp', :git => 'https://github.com/webmproject/libwebp.git', :branch => 'master'
    # pod 'libwebp', :git => 'https://github.com/webmproject/libwebp.git', :branch => '1.0.1'
    # pod 'libwebp', :git => 'https://github.com/webmproject/libwebp.git', :tag => 'v1.0.1'
    # pod 'libwebp', :git => 'https://github.com/webmproject/libwebp.git', :commit => '928a75d'
    # pod 'libwebp', :podspec => 'https://example.com/JSONKit.podspec'
    # open ~/.cocoapods/repos/master/Specs/1/9/2/libwebp
    # 修改本地libwebp地址为 https://github.com/webmproject/libwebp.git
    pod 'libwebp', '~>1.0.0'
    pod 'MJRefresh', '~> 3.1.15.7'
    # 5.0 不支持 iOS 9
    pod 'Kingfisher', '~> 4.10.1'
    # FPS
    pod 'GDPerformanceView-Swift', '~> 2.0.2'
    
    pod 'RxSwift', '~> 4.4.0'
    pod 'RxCocoa', '~> 4.4.0'
    pod 'Result', '~> 4.0.0'
    pod 'RxAlamofire', '~> 4.3.0'
    pod 'Moya', '~> 12.0.1'
    pod 'Moya/RxSwift', '~> 12.0.1'
    pod 'RxAlamofire', '~> 4.3.0'
    pod 'RxDataSources', '~> 3.1.0'
    # 为了更加方便添加点击事件
    pod 'RxGesture', '~> 2.1.0'
    # pod 'ObjectMapper', '~> 3.4.2'
    # pod 'HandyJSON', '~> 4.2.1'
    pod 'SwiftyJSON', '~> 4.2.0'
    pod 'SVProgressHUD', '~> 2.2.5'
    # 路由
    pod 'CTMediator', '~> 25'
    # redux
    pod 'ReactorKit', '~> 1.2.1'
    # pod 'RxAppState', '~> 1.3.0'
    pod 'NSObject+Rx', '~> 4.4.1' # 为了使用rx_disposeBag
    
    
  target 'DouyinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DouyinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            end
            
            # Fix libstdc++.6在Xcode10编译报错问题
            if target.name == "Pods-SomeTarget"
                xcconfig_path = config.base_configuration_reference.real_path
                xcconfig = File.read(xcconfig_path)
                new_xcconfig = xcconfig.sub('stdc++.6', 'c++')
                
                File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
            end
            update_config config
            if config.build_settings['PRODUCT_NAME'] == 'Result'
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end
end

# Pod设置 =================================

def update_config (config)
    
    config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
    config.build_settings['SWIFT_VERSION'] = '4.2'
    
    # config.target_attributes["LastSwiftMigration"] = "0830"
    
    if config.name == "Debug" then
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
    end
    
    #    elsif config.name == "Release" then
    #    config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
    #    config.build_settings['SWIFT_VERSION'] = '3.0'
    #    end
end
